<?xml version="1.0" encoding="utf-8"?><Database Name="XMLtoDATABASE" Class="XmlDataContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=shreekeshm\mssqlserver2012;Initial Catalog=XMLtoDATABASE;User ID=sa" SettingsObjectName="DataContextClassLibrary.Properties.Settings" SettingsPropertyName="XMLtoDATABASEConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Company" Member="Companies">
    <Type Name="Company">
      <Column Name="Company_Id" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Company_Department1" Member="Department1s" ThisKey="Company_Id" OtherKey="Company_Id" Type="Department1" />
      <Association Name="Company_Employee1" Member="Employee1s" ThisKey="Company_Id" OtherKey="Company_Id" Type="Employee1" />
    </Type>
  </Table>
  <Table Name="dbo.Department" Member="Departments">
    <Type Name="Department">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DepartmentName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Department_Department1" Member="Department1s" ThisKey="ID" OtherKey="Departments_Id" Type="Department1" />
      <Association Name="Department_Employee" Member="Employees" ThisKey="ID" OtherKey="DepartmentId" Type="Employee" />
    </Type>
  </Table>
  <Table Name="dbo.Departments" Member="Department1s">
    <Type Name="Department1">
      <Column Name="Departments_Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Company_Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="Company_Department1" Member="Company" ThisKey="Company_Id" OtherKey="Company_Id" Type="Company" IsForeignKey="true" />
      <Association Name="Department_Department1" Member="Department" ThisKey="Departments_Id" OtherKey="ID" Type="Department" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DepartmentId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Salary" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="Employee_Employee1" Member="Employee1s" ThisKey="ID" OtherKey="Employees_Id" Type="Employee1" />
      <Association Name="Department_Employee" Member="Department" ThisKey="DepartmentId" OtherKey="ID" Type="Department" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Employees" Member="Employee1s">
    <Type Name="Employee1">
      <Column Name="Employees_Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Company_Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="Company_Employee1" Member="Company" ThisKey="Company_Id" OtherKey="Company_Id" Type="Company" IsForeignKey="true" />
      <Association Name="Employee_Employee1" Member="Employee" ThisKey="Employees_Id" OtherKey="ID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
</Database>